-- ==========================
-- V2__create_payment_order.sql
-- H2-compatible schema
-- ==========================

-- ============================
-- V1: PaymentOrder main table
-- ============================

CREATE TABLE payment_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id VARCHAR(100) NOT NULL UNIQUE,
    client_id VARCHAR(50) NOT NULL,

    amount DECIMAL(18,4) NOT NULL,
    currency VARCHAR(3) NOT NULL,

    beneficiary_name VARCHAR(70) NOT NULL,
    beneficiary_address VARCHAR(105) NOT NULL,

    destination_account VARCHAR(35) NOT NULL,
    country_bank VARCHAR(2) NOT NULL,

    bic VARCHAR(11),
    bank_name VARCHAR(255),
    bank_address VARCHAR(255),

    transaction_remark VARCHAR(500),
    remark_mode VARCHAR(10) NOT NULL DEFAULT 'MANUAL',
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- Indexes
CREATE INDEX idx_payment_order_client ON payment_order (client_id);
CREATE INDEX idx_payment_order_status ON payment_order (status);
CREATE INDEX idx_payment_order_bic ON payment_order (bic);

-- =====================================
-- V2: Key-value tokens for PaymentOrder
-- =====================================

CREATE TABLE payment_order_tokens (
    payment_order_id BIGINT NOT NULL,
    token_key VARCHAR(50) NOT NULL,
    token_value VARCHAR(255),

    PRIMARY KEY (payment_order_id, token_key),

    CONSTRAINT fk_payment_order
        FOREIGN KEY (payment_order_id)
        REFERENCES payment_order(id)
        ON DELETE CASCADE
);

-- ======================
-- V3: BIC directory table
-- ======================

CREATE TABLE bic_directory (
    bic VARCHAR(11) PRIMARY KEY,
    bank_name VARCHAR(255),
    bank_address VARCHAR(255),
    country VARCHAR(2)
);

-- ============================================
-- V4: Manual override audit logging (optional)
-- ============================================

CREATE TABLE manual_override_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_order_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id VARCHAR(50),
    comment TEXT,

    CONSTRAINT fk_manual_override_payment
        FOREIGN KEY (payment_order_id)
        REFERENCES payment_order(id)
        ON DELETE SET NULL
);
